# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-ast
    # - id: double-quote-string-fixer
    - id: debug-statements
    - id: check-toml
    - id: check-json
    - id: check-xml
    - id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: "6.0.0"  # Check for the latest version
    hooks:
      - id: isort

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.4  # Check for the latest version
  hooks:
    - id: ruff
    - id: ruff-format  # Optional: Auto-format your code

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0  # Use the latest stable version
  hooks:
    - id: mypy
      args: ["--strict"]

- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  -   id: flake8
      name: flake8
      types: [python]
      args:
      -   --max-line-length=100
      -   --ignore=E203,E501,W503

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
    language_version: python3.10
